global:				# génériques
  resolve_timeout: 2m
  smtp_require_tls: false

route:				# règles de déclenchement
  group_by: ['instance', 'severity']
  group_wait: 10s		# temps d'attente avant notification du group
  group_interval: 1m		# délai par rapport aux alertes du même groupe
  repeat_interval: 5s		# attente avant répétition
  receiver: 'email-me'
  routes:
    - match:
        alertname: Trop_2_load

receivers:
  - name: 'email-me'
    email_configs:
      - to: "chaine.xavki@gmail.com"
        from: "chaine.xavki@gmail.com"
        smarthost: "smtp.gmail.com:465"
        auth_username: "chaine.xavki@gmail.com"
        auth_identity: "chaine.xavki@gmail.com"
        auth_password: "Xavki12*"
