spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:h2:mem:stockdb
    username: sa
    password: password
    driverClassName: org.h2.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show:
        details: always
  zipkin:
    tracing:
      endpoint: http://tempo-service:9411/api/v2/spans
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
server:
  port: 8081

service:
  payment:
    url: http://${SERVICE_PAYMENT_HOST}:${SERVICE_PAYMENT_PORT}/api/carte-credits
    numeroMarchant: 9898656789012345
